sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Xecius/udemy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Xecius/udemy-docker-react npm run test